name: Keep Database Alive
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          curl -f https://kirticard.telzac.site/api/health || echo "Health check failed"
          
      - name: Log result
        run: echo "Database ping completed at $(date)"
